import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";
import { Input, ThemeProvider } from "pix0-core-ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider><html lang="en">
      <body className={inter.className}>
        <div className="mt-2">
          <Input/>
        </div>
        {children}
      </body>
    </html></ThemeProvider>
  );
}
